name: branch-name-alert

on:
  - delete

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    env: 
      GITHUB_CONTEXT: ${{ toJson(github) }}
      VARIABLE: "my value"
    if: ${{ !startsWith(github.ref_name, 'DASRE') && !startsWith(github.ref_name, 'test') }}
    container: 
      image: node:20-alpine3.16
    steps:
      - name: print
        run: |
          echo "GITHUB_REF_NAME: ${GITHUB_REF_NAME}"
          echo ${GITHUB_BRANCH}
      - name: send a slack Message
        uses: docker://technosophos/slack-notify
        env:
          SLACK_WEBHOOK: ${{ secrets.GA_STANDARDS_PAT }}
          SLACK_MESSAGE: |
            "A new branch that does not follow the GitHub Branch naming standards for the Datatools Team has just been created. This will get deleted in the next 48 hours.
            Any PRs from thi branch will be blocked and not allowed to merge.
            Please create a branch that follows the naming convention.
            Naming convention - The branch name should start with the Jira ID, or it should be one of the whitelisted names.
            Please find the whitelisted names in Line 1 of ./.github/workflows/cleanup.py file in this repository."