name: branch-name-alert

on:
  - push

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    env: 
      GITHUB_CONTEXT: ${{ toJson(github) }}
      GITHUB_BRANCH: ${{ github.GITHUB_REF }}
    if: ${{ !startsWith(github.ref_name, 'DASRE') && !startsWith(github.ref_name, 'test') }}
    container: 
      image: node:20-alpine3.16
    steps:
      - name: send a slack Message
        uses: docker://technosophos/slack-notify
        env:
          SLACK_WEBHOOK: ${{ secrets.GA_STANDARDS_PAT }}
          SLACK_MESSAGE: |
            "The branch ${{GITHUB_BRANCH}} does not follow the GitHub Branch naming standards for the Datatools Team. This will get deleted in the next 48 hours.
            Please create a branch that follows the naming convention.
            Naming convention - The branch name should start with the Jira ID, or it should be one of the whitelisted names.
            Please find the whitelisted names in Line 1 of ./.github/workflows/cleanup.py file in this repository."