name: branch-name-check

on:
  push:
  create:
  pull_request:
      types: [opened]

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    env: 
      GITHUB_CONTEXT: ${{ toJson(github) }}
      GITHUB_BRANCH: ${{ github.refname }}
      GITHUB_REPOSITORY: ${{ github.repository }}
      SLACK_GROUP: ${{ secrets.GA_STANDARDS_SW }}
    if: |
      ${{ 
      !startsWith(github.ref_name, 'DASRE') && 
      !startsWith(github.ref_name, 'master') && 
      !startsWith(github.ref_name, 'test') 
      }}
    
    steps:
      - name: print branch
        if: github.event_name == 'push'
        shell: python
        run: |
          import os
          branch = os.getenv('GITHUB_BRANCH')
          repository = os.getenv('GITHUB_REPOSITORY')
          print (branch)
          print (repository)
      - name: send a slack Message
        if: github.event_name == 'create'
        shell: python
        run: |
          import os
          slack_webhook = os.getenv('SLACK_GROUP')
          print (slack_webhook)
          import requests
          import json
          payload = {
              'text': 'Hello how are you?'
          }
          headers = {
              'Content-Type': 'application/json'
          }
          response = requests.post(slack_webhook, data=json.dumps(payload), headers=headers)
          response.raise_for_status()
          print('Slack message sent successfully!')
      - name: stop pull request
        if: github.event_name == 'pull_request'
        run: exit 1