name: stop-pull-request

on:
  delete

jobs:
  stoppr:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.ref_name, 'DASRE') && !startsWith(github.ref_name, 'test') }}
    steps:
      - name: print branch name
        run: echo "hello world"