name: stop-pull-request

on:
  push:
  pull_request:
    types: [opened]

jobs:
  stoppr:
    runs-on: ubuntu-latest
    steps:
      - name: print branch name
        run: |
          echo ${{toJson(github).ref_name}}